### ISSUE TITLE
After putting the url in, nothing happens.

### ISSUE THREAD

**Issue by Colasice** [bsides/horizoverlay#1]
After I put the url in, nothing happens. I hit reload overlay and at the bottom it says, "Mini parse: Browser Console: The key Shrink-to-fit is not recognized and ignored.

**Comment by eparsyl** [comment]
I also get this error.

8/8/2017 7:37:26 PM: Info: Horizon: BrowserConsole: The key "shrink-to-fit" is not recognized and ignored. (Source: https://bsides.github.io/horizoverlay/, Line: 1)

Altho you can still drag the corner and resize it as you want to stretch it out, on initial load it shows jumbled up in the top left corner.

**Comment by bsides** [comment]
Did you guys hit anything to make the data be shown? Be sure to be next to a Dummy or any mob. Without data nothing is shown as this is really minimalistic.

**Comment by Colasice** [comment]
I did. After I enabled it, I went to central shroud and used fleche on a water sprite. Nothing happened.

**Comment by bsides** [comment]
@Colasice that's so weird :( could you please check if you're with the latest version of the Overlay plugin (0.3.3.13) ([link here](https://github.com/hibiyasleep/OverlayPlugin))? Also, if you could check if any other overlay is working would be great (this one in the url field: https://hibiyasleep.github.io/kagerou/overlay)

The error code mentioned isn't anything to worry. It's not an error, just an info message. I'll get rid of it anyway.

**Comment by Colasice** [comment]
So it says I'm using 0.3.3.12. I clicked your link but I couldn't find a way to download it. When I scrolled down and saw the link for download down there it took me to version 0.3.3.9. To answer your other question, kagerou works just fine. I was using it before I tried yours.

**Comment by Colasice** [comment]
I figured out where to find the 0.3.3.13 and the overlay is working now. Thanks.

**Comment by bsides** [comment]
@Colasice Thanks for testing, sorry for not pointing direct to the release page... I often forget Github has a learning curve.

I'm working on making more visual the first load of the plugin (like a setup). Will notify this issue once it's done.
