### ISSUE TITLE
ACTWebSocket sorting is reverse

### ISSUE THREAD

**Issue by hx41455** [bsides/horizoverlay#104]
Using actWebSocket for streaming and the sorting is reversed, least dps to highest. No way to configure either? Event settings were sorted by DPS in descending order already. Event settings don't seem to effect it at all.

![image](https://user-images.githubusercontent.com/43611161/84565542-dd8c7e00-ad37-11ea-95ec-068e750bacbf.png)

**Comment by bsides** [comment]
Hi @hx41455, we recently fixed some bugs, could you please test it and reopen this issue if the error persist? Thank you!

**Comment by hx41455** [comment]
Still seems to be doing it. I did test another overlay (Ember) in websocket to see if it's the websocket causing the problem, but it ember sorted correctly.
