### ISSUE TITLE
Streamer Mode

### ISSUE THREAD

**Issue by sq34k** [bsides/horizoverlay#115]
Hi there im a twitch streamer and love this overly so much

would it be possible to add an option to hide names or display them as initials please as this is required for streamers to do now and i am unable to show this overlay while streaming <3

**Comment by bsides** [comment]
Hi @sq34k ! This is a nice request, but as of now I am unable to play the game. I'll leave it open so maybe someone else can grab it and open a PR.

Thanks!

**Comment by Enubia** [comment]
@bsides i've gone ahead and implemented an option to blur character names excluding your own of course
