### ISSUE TITLE
Max hit display: Skills with hyphenated names being parsed incorrectly

### ISSUE THREAD

**Issue by MeiHantei** [bsides/horizoverlay#117]
For example, the monk's Six-Sided Star: <img width="118" alt="Advanced_Combat_Tracker_OlLxvudQcV" src="https://user-images.githubusercontent.com/79325281/108529021-08a17700-72a2-11eb-95f3-d39016fd5ccb.png">

Note that instead off the skill "Six-Sided Star" being displayed as dealing "69909" damage, the skill "Six" is being displayed as dealing "Sided Star:-69909" damage. 

Tri-disaster displays similarly, and I'm sure if there are any other hyphenated skills, they'll be affected as well.

Skills with colons in their name, such as Kaeshi: Setsugekka, are being parsed correctly. Off the top of my head, I can't think of any other special characters that would cause this edge case.

**Comment by bsides** [comment]
Hi @MeiHantei, thanks for the report, that's a very good catch. I'm going to need some help here to solve this, I hope someone can open a PR.
