### ISSUE TITLE
Overlay does not update numbers, requires manual reload

### ISSUE THREAD

**Issue by Cidtaru** [bsides/horizoverlay#12]
Hi there,

I'm quite sure that I'm missing something really small and stupid here.

I've setup the overlay, but when I go to engage anything the numbers do not update and just show infinite dps along with the encounter clock just being stuck at 0:00. If I press reload overlay in the ACT plugins menu, then it'll pull updated numbers but will remain stuck at that point until I press reload overlay again.

Any ideas on what I did wrong?

**Comment by bsides** [comment]
@Cidtaru I just noticed it myself. I'm looking into it, sorry for the trouble and thanks for the report :)

**Comment by bsides** [comment]
EDIT: I also bumped an older version (without zoom scale) to the url, - should be working - while I fix the new one.

**Comment by bsides** [comment]
Please reopen if the issue is still there, I tested and it was ok 👍
