### ISSUE TITLE
cactbot started reporting errors after updating

### ISSUE THREAD

**Issue by Viking602** [bsides/horizoverlay#142]
cactbot started reporting errors after updating
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'. (Source: , Line: 0)
[2021/12/5 3:28:56] Info:  BrowserConsole: Uncaught Error: Cannot find module './sge.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[2021/12/5 3:28:58] Info:  BrowserConsole: Error: Cannot find module './sge.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1
![image](https://user-images.githubusercontent.com/27732503/144722211-2d134805-7183-4f4d-abb5-1b97670c9c7f.png)

**Comment by MyTechnoHunter** [comment]
no, the first line is not anything to do with this overlay.. the second bit is dealing with a missing icon for the new endwalker jobs.. please have the author update!

**Comment by ngld** [comment]
If you change the following section
https://github.com/bsides/horizoverlay/blob/4d402abffd62a59521d6f8377d1de936eddb696b/src/CombatantHorizontal.js#L61-L75
to this instead
```js
if (config.showJobIcon) {
  jobIcon = './'
  if (data.Job === '') {
    // well there are a lot of things that doesn't have a job, like summoner's pets and alike. Lets assume them all.
    let newIcon
    newIcon = 'error'
    for (const otherIcon of otherIcons) {
      if (name.indexOf(otherIcon) >= 0) newIcon = otherIcon
    }
    jobIcon += newIcon
  } else {
    jobIcon += data.Job.toLowerCase()
  }
  try {
    jobIcon = images(`${jobIcon}.png`)
  } catch (e) {
    console.error(e);
    jobIcon = null;
  }
}
```
it'll still log errors for the missing icons but at least it'll work. The icons for the new jobs are still missing, of course.

**Comment by ekumlin** [comment]
I created PR #143 to add the role colors and icons, as well as patch the code above so that future job additions don't break the overlay.

**Comment by Viking602** [comment]
> I created PR #143 to add the role colors and icons, as well as patch the code above so that future job additions don't break the overlay. Tested locally while waiting in queue (lol) using a dungeon run I had just finished:
> 
> ![image](https://user-images.githubusercontent.com/1350074/144731132-874f45dd-814a-4cb6-9df5-3a03e2a90691.png)

Great! Thanks!

**Comment by bsides** [comment]
Thank you all very much for the contribution!
