### ISSUE TITLE
Update Github Pages version

### ISSUE THREAD

**Issue by lnmiltz** [bsides/horizoverlay#154]
A couple months ago [this PR](https://github.com/bsides/horizoverlay/commit/6603787b0a41fc97bb29c5d6cdeb2801c33d6436) was merged, but it's not reflected in the public version hosted at https://bsides.github.io/horizoverlay. Can the github pages site be updated with the new changes?

The second to last commit added reaper/sage icons, so it looks like github pages is only one commit behind.

**Comment by bsides** [comment]
This should be fixed. Please let me know if it doesn't @lnmiltz
