### ISSUE TITLE
Limit Break DPS

### ISSUE THREAD

**Issue by tiagofox** [bsides/horizoverlay#16]
DAMN LIMIT BREAK OMFG REMOVE IT 💢 

no, please, its relevant for me :3 its just using one more slot on overlay

**Comment by bsides** [comment]
I do believe it's relevant but shouldn't be an element like a player is. Maybe another thing entirely? Or just show it along with Total DPS, something like "Limit Break: 3%", just text

_Sent from my Samsung SM-A510M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bsides** [comment]
https://github.com/bsides/horizoverlay/commit/d8736db92e2417ccaf51e6579e189c341d5a685a this removed *Limit Break* from being an item - **and itself altogether in the process**. 

Next step will be inserting it together in the bottom bar with `Duration` and `Total DPS`. Hopefully it'll look good enough. I'm just waiting the Discord feature to do its thing 😉

**Comment by bsides** [comment]
Fixed in the last `discord` branch ;)
