### ISSUE TITLE
One-color DPS Bar

### ISSUE THREAD

**Issue by vocruen** [bsides/horizoverlay#17]
Hi, I'm having a weird issue where I tried to load the overlay and it looks like [this](http://imgur.com/wOyXXcu). I wondering why it isn't split kind of like in the other screenshots where the job/HPS is darker than the rest. Is there any way to fix this? 

As a side note, I do have 0.3.3.13 and updated to 0.3.3.14, and it still hasn't changed anything. 

I hope to hear from you soon!

**Comment by bsides** [comment]
Hi @vocruen, it's been reported already https://github.com/bsides/horizoverlay/issues/10 but I'll see what I can do in the next days. 

Thanks for reporting regardless.

**Comment by vocruen** [comment]
Sorry, I did view the old requests but the one similar to mine only noted
about the empty line on the YOU bar, not the fact that it was a solid
color. Forgive me for not assuming you picked up both as an issue.

You're doing great with the overlay, though! Thanks for sharing!

**Comment by bsides** [comment]
Thanks for the kind words @vocruen <3
