### ISSUE TITLE
Overlay parsing chocobos

### ISSUE THREAD

**Issue by tiagofox** [bsides/horizoverlay#23]
![image](https://user-images.githubusercontent.com/6744524/30001353-fab28e0c-9061-11e7-8e54-f2c0caba979c.png)

**Comment by bsides** [comment]
I don't really know what to do with this one - shouldn't they be parsed?

What I just discovered by looking at the picture is that their name isn't "Chocobo" like I supposed before, heh... so at least I should be able to fix their icon and colors. 

What colors should they have?
