### ISSUE TITLE
Settings not saving.

### ISSUE THREAD

**Issue by Neeksy** [bsides/horizoverlay#24]
This issue just started popping up yesterday for me, not sure if it came with a recent update or not because I haven't been online. For whatever reason regardless if I'm using the current or test build while in-game my own parse doesn't up white or display my name like I have it set to do.

<img src="https://i.imgur.com/ZYBlydH.png">

Oddly the moment I open the settings window to adjust this, it corrects itself? If it starts a new parse though it goes back to displaying it incorrectly until I open the settings window again. Not sure what's going on.

<img src="https://i.imgur.com/uiONZEp.png">

**Comment by bsides** [comment]
Hi @Neeksy, first of all thanks for reporting!

Now, I tried to replicate this many times but I still can't do it. You see, I save the settings in the overlay (which is a Chrome browser, so it has a thing called localStorage) - so if overlay plugin didn't change it, it should work. What version are you using? You can check it at Plugins > Plugin Listing https://puu.sh/xttwA/24d9db9062.png

Did you try to reset it? There's this button on the rightmost side: https://puu.sh/xttbV/86c380ba91.png

To check if it really removed data from overlay:
* Click the **Open dev tools** button https://puu.sh/xttdQ/014b76d0df.png
* Click the **Resources** tab
* On the left side, Local Storage > https://horizoverlay.now.sh
* On the righ side, right click and delete anything there

Close ACT just in case and reopen. Open the overlay, change any setting, hit something, see if it's saved by closing and opening act again. If it didn't, I'll need more data to test this. 

Last question, the last update was 4 days ago, were you on before that?

**Comment by Neeksy** [comment]
Thanks for answering, @bsides!

Alright, I went through all the steps you said. My plugin version is same as your screenshot provided, 0.0.3.14 so I suppose I can rule that out. I attempted resetting as well, but to no avail. Tried every combination of opening/closing ACT, resetting, changing different settings, but the same weird thing is going on. I can't possibly imagine what's causing it.

And yes! I believe I was using it before the update and I don't recall having any problems. I can't say for sure if it's actually related to the update, I'm thinking it may just be something screwy going on my end.

**Comment by bsides** [comment]
It's such a frustrating thing when this kind of thing happen 😢 

Well there are some extra things you could do, but let's rule out an important one. I uploaded the old version to the test url `https://horizoverlay-test.now.sh` so you can test this one and see if the same thing happens. If the same thing happen we know it's the new version and this overlay alone. 

Report back whenever you can please.

If you want to try other things: test other overlay ([kagerou](https://github.com/hibiyasleep/kagerou) is a good one), check your [ffxiv plugin](http://advancedcombattracker.com/download.php) version (a new one [released 3 days ago](https://github.com/ravahn/FFXIV_ACT_Plugin/releases)), check if your ACT is receiving data (can be done with other overlay or just checking the main ACT tab) - if not check if your ACT is going through windows firewall and DLLs are properly unblocked. Those are the things on the top of my head.

I'm really sorry you're experiencing this though, but if you have patience and time we can solve it :D

**Comment by Neeksy** [comment]
Alright, good news and bad news! The good news is... it's working like it should finally! The bad news is that the old version is the one that worked. Just in case I made sure my ffxiv plugin was up to date (it is) and my ACT is definitely receiving data and working with other overlays. So the plot thickens! Is there anything you'd like me to try to help debunk this?

**Comment by bsides** [comment]
Alright, it's most good news than bad then :D

Could you leave the dev tools open with its Console tab focused? It should show any errors it may be having. Then, with it open, do stuff that should work but isn't and see if it throw any errors. Copy any errors from there and paste here please.

Another thing: if you didnt do it before, could you delete the mini parse and create it again? If you already did that nevermind.

**Comment by bsides** [comment]
Oh my god stop everything

**Comment by bsides** [comment]
it's just the name so I'm using a different name in ACT and I only checked for it... 
https://puu.sh/xtNFw/7555ec1d80.png

I think I'll this fixed today, I'm so sorry I made you pass through all of this :(

**Comment by bsides** [comment]
Ok so, I may have fixed this, could you test it again @Neeksy? 
**The regular url** `https://horizoverlay.now.sh` 

Thanks for your patience 😸

**Comment by Neeksy** [comment]
Just got home to give it a test drive and... the operation was a success! The overlay is back to working as it should be. Thank you so much for working with me to figure out the problem. :)

<sub>(As a side note I know my overlay probably looks extraordinarily tiny but that's because I personally open the dev tools to make the font size like 11px. I know a lot of people requested it bigger, but I personally prefer smaller haha.)</sub>

<img src="https://i.imgur.com/swSoAvo.png">

**Comment by bsides** [comment]
Hahaha Thanks @Neeksy :3 
That Lala looks so cute!

BTW I'm going to make that font size an option in settings pretty soon™ \o/
![](http://68.media.tumblr.com/51c149e29cfe270b8b37db0818d4fdcb/tumblr_osnne3oyaK1u9t5z9o1_540.gif)
