### ISSUE TITLE
Limit number of shown combatants?

### ISSUE THREAD

**Issue by Neeksy** [bsides/horizoverlay#27]
I use this overlay to conserve on space and avoid clutter on my screen, but it becomes sort of a cluttered mess if it attempts to display more than 8 people (occasionally it picks up chocobos, other alliance members, etc). Is there some way or a possibility I can make it display only whoever the highest 8 readings are? At the moment if it does exceed 8 within the space I have it limited to the boxes just get kinda squished together.

**Comment by bsides** [comment]
Hi @Neeksy,

It sure is possible, the data given by ACT can be processed before throwing it to the overlay. The only impediment right now is that I don't have a subscription to test it inside the game. I'll be coming back soon though, not more than 10 days or so. 

I'll try to add this request before this time, if you could test that would be awesome. I'll let you know.

Thanks for opening this!

**Comment by bsides** [comment]
One other thing on top of my head that is worth mentioning is that if the user doesn't merge the data from pets/chocobos in FFXIV Plugin settings, this can be troublesome. 

- Just something to myself to not overlook -

**Comment by bsides** [comment]
Could you please test it at https://build-ninvrvqzmg.now.sh/ ? Just put it in your ACT, open Settings and change the number of Combatants you want to be shown in the Overlay. It's ordering by damage so if your Chocobo does more damage than someone else (lol?) this someone else won't be shown in case there are more than the number of max combatants... 

I think this should solver it. If you have anything else let me know!

PS - I'm awaiting for a test before releasing for 3 days, afterwards I'm just releasing it.

**Comment by Neeksy** [comment]
It works wonderfully! I just ran a test run of Labyrinth and it successfully prevented from showing other alliance members I healed; I switched it to 9 real quick to make sure there was extra people and then put it back to only displaying 8.

Also as a note the 80% size is perfect for my screen and saves me from having to manually make it smaller. Thank you very much. C:

**Comment by bsides** [comment]
Awesome, I'm releasing it soon then! My screen was also needing that 80% that's why I put it. I'm going to put an input there in a next release too because those numbers are really not that great.

Thanks for testing! ☺️
