### ISSUE TITLE
Overlay Link Broken, Offline version unusable

### ISSUE THREAD

**Issue by AngryMustache** [bsides/horizoverlay#28]
Would rather use it locally for when this happens but the now.sh link no longer works for overlay and offline version doesn't load, even when following instructions nothing shows up.

**Comment by bsides** [comment]
Is it working now?

**Comment by AngryMustache** [comment]
It was earlier, not working again.

**Comment by AngryMustache** [comment]
Since the hotfix this week, hasn't worked much if at all

**Comment by bsides** [comment]
I don't have a subscription since early October so I can't fix this right now. I'll get back to it once I have time and $, i'll post back here.

**Comment by AngryMustache** [comment]
I've since been able to get the offline version semi-working, but when you right click the overlay the window it opens is a file directory of the c:/ drive, I can't find anyway to fix that as of yet. I had to edit the relative links in the index.html file to get the overlay to show up, just can't open the settings.

changed "/static/css/main.b185683b.css" to "./static/css/main.b185683b.css"
changed "/static/js/main.b30584aa.js" to "./static/js/main.b30584aa.js"

**Comment by bsides** [comment]
I'm sorry @AngryMustache, I'm not with the time to check upon this right now, I'm not even with a subscription. Whenever I get the time & subscription I'll let you know. Thank you for the close fix though!

**Comment by Paradox924X** [comment]
@AngryMustache Modify /static/js/main.b30584aa.js and find this snippet:
window.open("/#/config"

and simply remove the leading '/' to make that part of the code look like:
window.open("#/config"

Now the config file will load correctly on right-click, though the changes made won't apply live -- at least, they didn't for me. Modify the config as you see fit, and then just hit 'the Reload Overlay' button in ACT/Plugins/OverlayPlugin.dll/Mini Parse and it will reload with the updated config.

**Comment by bsides** [comment]
That error must be happening because of the hashtag route. I did like this because I couldnt make it work on now.sh without it - but it brings another problem, which is caching the answers and never reloading.

Maybe after the update we could make a function to call the page to reload() itself?

**Comment by bsides** [comment]
I promised to come back and I am. I just tested the URL with ACT and everything is working fine. The offline version is just a plus so I'm flagging this as an enhancement until then. If anything stop working please let me know :+1:

**Comment by bsides** [comment]
PS - Please report anything related to offline version in this other issue: https://github.com/bsides/horizoverlay/issues/25
