### ISSUE TITLE
version 2

### ISSUE THREAD

**Issue by tiagofox** [bsides/horizoverlay#5]
Warning: Failed prop type: Invalid prop `isActive` of type `string` supplied to `Overlay`, expected `boolean`.
    in Overlay (at index.js:48)
    in Route (at index.js:48)
    in Switch (at index.js:47)
    in Router (created by BrowserRouter)
    in BrowserRouter (at index.js:46)
    in Root (at index.js:58)

**Comment by bsides** [comment]
https://github.com/bsides/horizoverlay/blob/master/src/Overlay.js#L14 Really should be a boolean but what the hell, right?
