### ISSUE TITLE
Display boss name in leiu of encounter

### ISSUE THREAD

**Issue by MorningstarCel** [bsides/horizoverlay#59]
Would an option to display the boss rather than encounter in the overlay be possible?

**Comment by MorningstarCel** [comment]
Got it with .GetStrongestEnemy(combatant) - Nevermind!

**Comment by bsides** [comment]
Hi! I see you found an API command there. Cool! Did you fork/use it locally? I may put it into the repo if you could PR it. I’m not playing the game right now, but If you could test it would be no problem.

Thank you!

**Comment by MorningstarCel** [comment]
Hello! 

Right now I'm just playing with it locally. Specifcally because of the 'send to discord' function - so far it's cleaned up to use a discord embed, looks a lot nicer, and an alpha state of connecting to the fflogs api and returning a lookup for damage percentile in the fight vs all other classes and returning is as a colour to the embed for that player. While it's somewhat working, the biggest issue presented is sending the data for the entire fight, as right now the overlay only manages to hold data between endEncounter, which doesn't account for protracted downtime phases.

 Not to mention matching zones as they're displayed in ACT to zones through the fflogs api is a pain too. x)
