### ISSUE TITLE
Little requestment

### ISSUE THREAD

**Issue by 1lkm** [bsides/horizoverlay#60]
In DPS, can you make option that can sum summoner's DPSand Carbuncle's DPS?

Is there anything that can reset DPS collected?
Sometimes there is Error in DPS collecting or User wants to Reset DPS..

**Comment by bsides** [comment]
Hi there!

The DPS from the summoner and its pet can be summed from the ACT Interface. In the FFXIV plugin, be sure to check the option to do that. I’m not in my PC right now to show you a sceeenshot if it, but it shouldn’t be too hard to find. Let me know if you don’t.

About the reset option, you can do it via ACT interface as wel. The plugin does have an option but last time I checked it was bugged. I’m not playing the game anymore (financial issues) but I can look at that again sometime in the near future.

**Comment by bsides** [comment]
I'm closing this right now as it saw little advance from the plugins. Also, the overlay isn't updated anymore unfortunately.
