### ISSUE TITLE
Overlay closing ACT on first use

### ISSUE THREAD

**Issue by Mizurachi** [bsides/horizoverlay#61]
Good evening! I had just stumbled across your overlay and I would really like to use it however when I go to right click the box to change the settings or re-position the overlay it would just pop open a white window and then just shut ACT down entirely as well as delete itself from the Plug-in upon re-opening. I have the latest Overlay Plug-in installed as well

**Comment by bsides** [comment]
Hi @Mizurachi!

I couldn't reproduce this kind of behavior because I'm not playing the game at the moment (don't have subscription), but I never saw this error before. Are all plugins in their latest version? Could you show me some screenshots of the plugin with devtools open?

Thanks!

**Comment by Mizurachi** [comment]
![plug-ina](https://user-images.githubusercontent.com/43922032/46900202-bfcc8e80-ce5b-11e8-8a2a-09c8baa3d720.PNG)
Here are the plug-ins I'm currently using when trying to use Horizon, It's possible that I might need more than what I have but I don't know where to find them if I need more

**Comment by bsides** [comment]
Hi @Mizurachi sorry for the very late reply. I believe the issue got solved but if it isn't please reopen this issue and I'll look into it this week.

Thanks!
