### ISSUE TITLE
Missing icons/errors for BLU (Blue Mage)

### ISSUE THREAD

**Issue by someONEgood** [bsides/horizoverlay#65]
Any chance you could update horizoverlay for the new blue mage job?

**Comment by bsides** [comment]
Hi @someONEgood, I need to find the icon first... wondering where can I get those. But sure I will update it soon! Thanks for letting me know.

**Comment by someONEgood** [comment]
I can do the legwork there!
BLU: https://ffxiv.gamerescape.com/wiki/File:Blue_Mage_Icon_1.png

It would be great if you could add companions (chocobos) as well. Here's a few options:
https://ffxiv.gamerescape.com/w/images/4/4f/Player30_Icon.png
https://ffxiv.gamerescape.com/w/images/e/e4/Chocobo_Icon_7.png
https://ffxiv.gamerescape.com/w/images/a/a9/Chocobo_Icon_6.png

Thanks so much for this. You're overlay is fantastic. Very sleek and unobtrusive.

**Comment by bsides** [comment]
Thank you so much @someONEgood, will try to include those this weekend! 😸

**Comment by bsides** [comment]
@someONEgood it's finally fixed, thanks for your (and everyone's) patience.

Regarding chocobos and other, it's a little harder to fix since ACT isn't very uniform on what data it sends to me. I'll look into it another time. If you could, please add another issue for me about it 😸

**Comment by someONEgood** [comment]
Awesome work, thank you! Appreciate you taking the time to work on these updates.
Horizoverlay is the beeeeest.
