### ISSUE TITLE
Missing icons/errors for GNB and DNC

### ISSUE THREAD

**Issue by reinbei** [bsides/horizoverlay#69]
Possible to receive an update for GNB and DNC jobs? This is my favorite act overlay and would love an update for the new expansion :))

**Comment by bsides** [comment]
Of course! Would you mind sending me the icons in any way? Could be just a link for them, like @someONEgood once did in this issue https://github.com/bsides/horizoverlay/issues/65

Thanks in advance!

**Comment by reinbei** [comment]
Here you go! I appreciate it and I hope these work!

DNC: https://ffxiv.gamerescape.com/wiki/File:Dancer_Icon_1.png
GNB: https://ffxiv.gamerescape.com/wiki/File:Gunbreaker_Icon_1.png

**Comment by bsides** [comment]
Hi @reinbei, thanks for your contribution! Assuming the icons are right I’ll try to update it today. I’ll let you know by closing this issue then. Thanks again!

**Comment by bsides** [comment]
Fixed @reinbei, could you please test them? Thank you again!

**Comment by reinbei** [comment]
@bsides It works perfectly! Thank you!
