### ISSUE TITLE
Scaling settings

### ISSUE THREAD

**Issue by Djuu** [bsides/horizoverlay#7]
Having scaling settings would be awesome.

As a 4k player, I'm having a hard time reading the values without extra focusing because it's too small.

**Comment by bsides** [comment]
That's a nice one to have indeed. A little hard to achieve automatically but maybe a scaling bar that would adjust everything percentage based would help?

**Comment by Djuu** [comment]
That would be perfect I guess :)

**Comment by bsides** [comment]
@Djuu give it a try 😸

**Comment by Djuu** [comment]
Perfect ! 👍
