### ISSUE TITLE
GNB/DNC missing role colors

### ISSUE THREAD

**Issue by Neeksy** [bsides/horizoverlay#70]
Good news! They're displaying properly with icons and all, but they seem to be missing their role colors. GNB is tank and DNC is dps, of course.

![image](https://user-images.githubusercontent.com/31013479/60582873-43fad500-9d4f-11e9-8eec-a12564e7dbe0.png)

**Comment by bsides** [comment]
Oh that's right, I knew I was missing something. Will schedule some time tonight to fix it. Thanks!
