### ISSUE TITLE
Option to toggle alliance/party

### ISSUE THREAD

**Issue by Vitoire** [bsides/horizoverlay#73]
Hi there! 

Right now, when you use ACT with this overlay and run alliance content, it shows the 8 people that do the highest DPS of the entire alliance. But I don't care about the other two alliances and would like to know the highest hitting person in my party only.

Do you think such an option is possible to implement? It would help me and others out a lot!

Thanks, loving your overlay a lot <3

**Comment by bsides** [comment]
Hi @Vitoire!

One thing I know for sure is that when you setup the [FFXIV Plugin](https://github.com/ravahn/FFXIV_ACT_Plugin) you can filter which data goes through it - None (no filter), Party or Alliance data. If you filter for just party it will do what you want.

I don't know if I can get the alliance data from my side. The last time I checked I couldn't, but things may have changed, I'll research a little more into it.

**Comment by bsides** [comment]
I just checked, it's impossible for my part to know which people are from what. The only config is from FFXIV Plugin itself. Here's a screenshot where you can set it up:

![image](https://user-images.githubusercontent.com/87631/60935005-bcf1b380-a29e-11e9-93a8-0a0b16583f5e.png)
