### ISSUE TITLE
Dps Order

### ISSUE THREAD

**Issue by DaneelReventelov** [bsides/horizoverlay#78]
Before the patch the pg was in order of dps but now are totally random and impossible to follow in fight, is possibile to have the ordering back?

**Comment by bsides** [comment]
Hi @DaneelReventelov how are you?

I'm having trouble getting time to test these days but from where I know there is no problem in the ordering (like this screenshot from 2 days ago): 

![image](https://user-images.githubusercontent.com/87631/61586673-b130a780-ab50-11e9-971c-290a60e8df9b.png)

Coul you please detail you setup to me?
For example, mine's like this:

![image](https://i.imgur.com/BzStaWv.png)

![image](https://i.imgur.com/meZV4J2.png)

Thank you

**Comment by DaneelReventelov** [comment]
Stupid me, really really sorry, I clicked for mistake on sorting type. 
These are bad days for ACT, many update and old plugins with problems that ruins the config files and I started top speed thinking the same now but is 100% my fault, really sorry and thank you very much for your skin, is the best and for me is part of my FF gui, impossible to play without it :)

**Comment by bsides** [comment]
No problem @DaneelReventelov, glad you worked it out! Anything let me know 👍
