### ISSUE TITLE
Discord Export Hitting Character Limit

### ISSUE THREAD

**Issue by Spathaian** [bsides/horizoverlay#84]
When exporting parses to a Discord Channel, the export is hitting the maximum message character limit (2000) and only displaying up to 2 players from an 8 player parse.

**Comment by bsides** [comment]
Hi @Spathaian!

I believe something changed from when I implemented this feature (2017) to now because even though I never heard of the limitation, the string shouldn't be more than 2k characters in any way.

I'm not having time to investigate this right now but will look into it sometime this month.

Thanks for letting us know!

**Comment by Spathaian** [comment]
Sorry, I just tried it again. It seems as if it will post now but not after an encounter.

I'll have to check to see if there's a setting in ACT that's ticked wrong.
![image](https://user-images.githubusercontent.com/53571117/62341820-39e10900-b4aa-11e9-9535-6aca56847a05.png)

**Comment by Burn-E99** [comment]
I hate to necro 2.5 year old issues, but the 2000 character limit is a real issue.  From my testing with the provided test data on an 8 player activity, the average message length that was generated was 1750 characters.  As soon as you try to use the webhook export on an alliance raid, there is no chance of that fitting under 2000 characters.

I've opened a PR to change the webhook from using raw text to a more modern Discord embed.  The Discord embed has a total character limit of 6000 and also has built-in formatting, allowing less of the character limit to be spent on formatting characters.

Here is a before/after comparison of the old method and my proposed method:
![image](https://user-images.githubusercontent.com/4857681/210944688-6f4f172a-b496-450b-930f-19c3b767a6e1.png)
