### ISSUE TITLE
In-game weird interaction

### ISSUE THREAD

**Issue by Amitay12** [bsides/horizoverlay#87]
Hey, up until today everything worked just fine for me. When I started ACT today, the overlay was not appearing properly, as if it's missing some of the images.

I'm able to interact with it, and open the settings, but non of the things I tried helped. I made sure to check and see if my friend was having an issue, but for him it was working perfectly fine.

I tried to re-install OverlayPlugin, close off ACT and run as admin, restart my computer. When I had used the URL in chrome, it worked just fine for me.

![Lclkdlr](https://user-images.githubusercontent.com/56096400/66087410-13118280-e580-11e9-9e2f-4303762928ff.png)

That's the overlay I'm seeing whenever I use the URL link. It is working and showing the dps, but it's all messed up :s
![Advanced_Combat_Tracker_eadOdYySy5](https://user-images.githubusercontent.com/56096400/66087620-c8443a80-e580-11e9-9dfb-079b557c5f9b.png)

**Comment by bsides** [comment]
Hi @Amitay12! Sorry for the delay in answering. Could you please try again? Sometimes the cache on these servers get in the way - and also I heard that the plugin was buggy around that time you tried it.

Thanks again!

**Comment by Amitay12** [comment]
I did just return from a break, and had tried it after the ACT update for the new patch, still giving the same issue...

**Comment by bsides** [comment]
After a year I must ask again, is it still an issue @Amitay12? Sorry for the huge delay in contacting back. If the issue persists, please reopen it. Thanks again!
