### ISSUE TITLE
Update for hibiyasleep overlay.

### ISSUE THREAD

**Issue by Krojack** [bsides/horizoverlay#89]
As others are changing over to the hibiyasleep overlay, I tried this and it mostly works however it has a light red background when you lock it in place and make it click through.  Will this be updated to use the new overlay?

https://github.com/hibiyasleep/OverlayPlugin

**Comment by bsides** [comment]
Hi @Krojack 
Sure, let me check it out and return to you soon. Thanks for reporting!

**Comment by bsides** [comment]
Oh wait, which one are you referring to again? You linked the plugin but it's the same from 2017 version.

**Comment by bsides** [comment]
Did you mean ngld's https://github.com/ngld/OverlayPlugin?
I did test with it (it improved greatly) but didn't notice those bugs. I'm going to try more but if  you could tell me when exactly that red background happens would be great.

Thanks for the report!

**Comment by Krojack** [comment]
Wow I failed so hard at this.

1. Yes I meant the ngld one.  I was swapping back and forth with the Cactbot that I got a little confused.
2. I found why your overlay was red.  I left the sample data enabled during the setup.  The overlay height wasn't large enough to see the warning message about the data being sample.  

I'll close this one for ya.  Thanks though and sorry to waste your time.

**Comment by bsides** [comment]
Glad you made it work :dancer: 
Thank you for pointing me to ngld, it's really going to be the default one.

Cheers!
