### ISSUE TITLE
DPS Order is random with NGLD OverlayPlugin in WebSocket

### ISSUE THREAD

**Issue by Felys1998** [bsides/horizoverlay#91]
I'm using the overlay via websocket in OBS and the DPS ordering is completely random. I understand that normally the overlay gets ordering from OverlayPlugin's settings but when using a browser source in OBS I do not have access to those options as OverlayPlugin's settings only apply to its internal rendering of the overlay.

![image](https://user-images.githubusercontent.com/2600400/69403723-2bfd0100-0cb0-11ea-98f1-6c68b80f80f8.png)

**Comment by Felys1998** [comment]
OK if anyone else gets stuck on this, NGLD's OverlayPlugin miniparse event source was defaulted to no sort order, you have to set it here to get them to display in order.

![image](https://user-images.githubusercontent.com/2600400/69472263-b7cc6700-0d5c-11ea-9c45-e4818c770a9e.png)

**Comment by bsides** [comment]
Thanks for that info @Felys1998 :+1:

**Comment by Kumicoo** [comment]
This is not an option for me. There is no "Sort descending". As said, NGLD Overlay

**Comment by Kumicoo** [comment]
https://prnt.sc/q3yp4y
