### ISSUE TITLE
ngld OverlayPlugin Issues

### ISSUE THREAD

**Issue by dravirus** [bsides/horizoverlay#93]
Hello!

I've updated my Overlay Plugin o ngld's version of it because of new cactbot, and i assume its the reason its been having all of these random issues. Right now, he's showing the correct numbers though a fight, but the order keeps swapping and jumping all the time on the list, making it impossible for me to identify how dps is really going or who is doing the biggest numbers. Is it possible to tell me if there's a way to make it work on the newest version, or i would need to go back on hibiya's version 100% guaranteed?
![image](https://user-images.githubusercontent.com/19843354/69706900-6f53d700-10d7-11ea-85bc-2ae05a795db6.png)

**Comment by bsides** [comment]
Hi @dravirus! Have you set up ngld source order correctly? Just asking because it's been a common mistake these days. Check the 2nd reply in this post https://github.com/bsides/horizoverlay/issues/91

If even though you're still getting this please let me know.

**Comment by dravirus** [comment]
OHH! I really didn't knew about this at all, and i'm not used to GitHub. Yeah, this instantly solved it, thank you very much! <3

**Comment by bsides** [comment]
> OHH! I really didn't knew about this at all, and i'm not used to GitHub. Yeah, this instantly solved it, thank you very much! <3

It's fine to not know anything, I'm here to help as well. I'm glad you made it work! \o/
