### ISSUE TITLE
job icon and dps show issue

### ISSUE THREAD

**Issue by aa663166396** [bsides/horizoverlay#96]
![QQ图片20200208000711](https://user-images.githubusercontent.com/34707153/74047297-11166f00-4a0b-11ea-87c6-838ad3d4da00.png)
after use ngld's overlayplugin,the dps font size seems is bigger and will coverd by job icon.The old one overlayplugin is ok, any way to fix?

**Comment by bsides** [comment]
Hi @aa663166396 this one is a hard to reproduce one. Maybe it's already fixed by ngld's cache? Could you report back if the error still exists? Thank you!
